### ISSUE TITLE
Mingw64

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/hwgui-r1908#1]
Consegui compilar com essa versão com Mingw64, entre tanto as telas ficam tudo bugadas. Como se não carregasse visualmente a tela.
Abaixo um exemplo:
![image](https://github.com/marcosgambeta/hwgui-r1908/assets/4009697/d22b2458-6e2b-4cc2-a9ae-5c15423ad7cd)

Estou analisando todos os cenários possíveis para minha realidade.
Acho melhor eu continuar tentando na versão abaixo, apesar de precisar de muitos ajustes ainda.
https://github.com/marcosgambeta/HWGUI

Tentei também compilar uma versão do BCC 64 do Harbour mas não tive sucesso, por alguma razão o BCC compila bem mais rápido meu sistema em harbour.

**Comment by marcosgambeta** [comment]
Talvez seja algo relacionado com a compilação em 64-bit. A compilação com MinGW64 não gera erros, mas gera uma quantidade considerável de avisos (warnings). Estou alterando o código para reduzir estes avisos do compilador. Caso teste novamente e o problema continue, avise por favor.

**Comment by marcosgambeta** [comment]
Apenas para complementar: apesar das mudanças realizadas no código-fonte, estou mantendo o comportamento original da HWGUI. Ou seja: comandos, classes e funções seguem inalterados. Quanto ao BCC64, vou tentar incluí-lo nos testes, junto com o MinGW 32/64 e o Visual C++ 32/64.

**Comment by sygecom** [comment]
Mestre, só para complementar.
Com 32 bits esse problema não acontece.

Infelizmente vou ter que focar no BCC para compilar, devido a demora ao compilar tudo. De momento vou tentar abrir testar o máximo em 32bits, depois foco apenas no 64 bits.

**Comment by sygecom** [comment]
Com as ultimas alterações que fez, resolveu esse problema com MIngw64
