### ISSUE TITLE
Tela preta abrindo com sistema

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/hwgui-r1908#3]
Marcos,
Para fim de teste com Harbour 3.2 + Mingw64, consegui compilar e estava abrindo uma tela presta junto.
Para evitar tive que colocar o código abaixo bem no inicio de: source\hcwindow.prg

```
#ifndef __XHARBOUR__
   #ifndef HB_NO_GTGUI
      REQUEST HB_GT_GUI_DEFAULT
   #endif
#endif

```
![image](https://github.com/marcosgambeta/hwgui-r1908/assets/4009697/db38602d-a405-43dd-88f3-2140f38434c0)

**Comment by marcosgambeta** [comment]
Poderia confirmar se a janela de console estava aparecendo mesmo sendo usado o arquivo hwgui.hbc ?

No arquivo hwgui.hbc, já é definido para usar a biblioteca gtgui:

```
{win}gt=gtgui
```

Eu não coloquei (ainda) a gtgui como default na HWGUI por causa da possibilidade dela ser usada com outros gt's. Exemplo: um sistema usando gtwvt como default e exibindo janelas de diálogo criadas com a HWGUI.

Uma forma de resolver esta situação seria colocar no sistema (antes da função MAIN):

```
#ifndef __XHARBOUR__
   REQUEST HB_GT_GUI_DEFAULT
#endif
```

Confirme, por favor, se a solução acima resolveria para você.

**Comment by sygecom** [comment]
Desculpa a demora, resolveu sim ! vou encerrar esse caso.
