### ISSUE TITLE
Navegação com TAB ou ENTER entre campos GET

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/hwgui-r1908#6]
Mestre,
Estou compilando com: HWG_USE_POINTER_ITEM

E a navegação entre os campos GET não está funcionando nem com ENTER(usando CLIPPER no INIT DIALOG) e nem com TAB, tem alguma dica para resolver isso ?

Esse problema só acontece quando estou compilando om HWG_USE_POINTER_ITEM, tanto em 32bits como 64bits.

Usando xharbour(versão git) e BCC 7.2

**Comment by sygecom** [comment]
Estou bem inclinado a seguir sem o uso HWG_USE_POINTER_ITEM, por que tenho bem menos problemas. Mas estou disposto a ajudar a estabilizar essa versão ai.

**Comment by marcosgambeta** [comment]
A compilação com HWG_USE_POINTER_ITEM está instável ainda. Apesar de não ocorrerem erros de compilação, os testes mostram comportamento errático. Sendo assim, acredito que seria melhor não usar esta flag, por enquanto. Mas você pode, conforme o tempo permitir, ir preparando seu sistema para funcionar com ponteiros. Quando a biblioteca estiver estável, poderá compilar com a flag ativada.

**Comment by marcosgambeta** [comment]
Leonardo, mantenha este tópico aberto, por favor. Assim fica como lembrete de um assunto pendente.

**Comment by marcosgambeta** [comment]
Enquanto o uso de ponteiros não ficar estável, fique à vontade para abrir tópicos relatando os problemas encontrados nos seus testes . Conforme o tempo permitir, vou testando aqui e procurando a causa dos problemas. O alvo é que funcione corretamente em ambas as situações (sem e com a flag), tanto em 32-bit quanto em 64-bit.

**Comment by sygecom** [comment]
Entendido mestre, está indo tudo muito bem com 32 e 64 bits sem HWG_USE_POINTER_ITEM
