### ISSUE TITLE
Problema com tamanho da tela usando Bcc 7.70 32bist

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/hwgui-r1908#7]
Marcos, bom dia.
Estou usando xharbour(versão do git) e BCC 7.70
D:\sistemas\sagi\trunk>bcc32.exe --version
Embarcadero C++ 7.70 for Win32 Copyright (c) 1993-2023 Embarcadero Technologies, Inc.
Revision 7.70.8683.38315

Se tiver alguma dica para ajustar isso na Hwgui agradeço.

Usando BCC 7.20
![image](https://github.com/user-attachments/assets/a6ebe1e9-c900-45d9-8f30-5c5d24e6a81e)

Usando BCC 7.70 ( ele cria janelas menores )
![image](https://github.com/user-attachments/assets/3c64c46f-8a27-4a29-8b96-cb0146970cb0)

**Comment by sygecom** [comment]
De momento aumentei mais 10 nos tamanho de ALTURA e LARGURA direto nas chamadas
Hwg_DlgBoxIndirect
e
Hwg_CreateDlgIndirect

Entre tanto achei estranho, segundo o chatgpt isso é devido a DPI, mas não consegui muita solução.

**Comment by marcosgambeta** [comment]
De acordo com a artigo abaixo, seria possível controlar a DPI através de arquivos 'manifest':
https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process
Mas seria preciso testar na prática para ver se corrige o problema.

**Comment by sygecom** [comment]
Tentei por esse manifest, mesmo assim ele não surge efeito, acho que vou ter que ajustar todas as telas do sistema mesmo. Obrigado.
